// Code generated by protoc-gen-go.
// source: group.proto
// DO NOT EDIT!

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	group.proto
	user.proto

It has these top-level messages:
	Group
	TrainingDirection
	User
	Users
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Period int32

const (
	Period_Zero Period = 0
	Period_Two  Period = 2
	Period_Four Period = 4
	Period_Five Period = 5
)

var Period_name = map[int32]string{
	0: "Zero",
	2: "Two",
	4: "Four",
	5: "Five",
}
var Period_value = map[string]int32{
	"Zero": 0,
	"Two":  2,
	"Four": 4,
	"Five": 5,
}

func (x Period) String() string {
	return proto.EnumName(Period_name, int32(x))
}
func (Period) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TrainingType int32

const (
	TrainingType_Bachelor     TrainingType = 0
	TrainingType_Master       TrainingType = 1
	TrainingType_Postgraduate TrainingType = 2
)

var TrainingType_name = map[int32]string{
	0: "Bachelor",
	1: "Master",
	2: "Postgraduate",
}
var TrainingType_value = map[string]int32{
	"Bachelor":     0,
	"Master":       1,
	"Postgraduate": 2,
}

func (x TrainingType) String() string {
	return proto.EnumName(TrainingType_name, int32(x))
}
func (TrainingType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Group struct {
	Id                      []byte                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TrainingDirectionId     []byte                     `protobuf:"bytes,2,opt,name=training_direction_id,json=trainingDirectionId,proto3" json:"training_direction_id,omitempty"`
	TrainingDirectionNumber int64                      `protobuf:"varint,3,opt,name=training_direction_number,json=trainingDirectionNumber" json:"training_direction_number,omitempty"`
	StartYear               int64                      `protobuf:"varint,4,opt,name=start_year,json=startYear" json:"start_year,omitempty"`
	Period                  Period                     `protobuf:"varint,5,opt,name=period,enum=user.Period" json:"period,omitempty"`
	TrainingType            TrainingType               `protobuf:"varint,6,opt,name=training_type,json=trainingType,enum=user.TrainingType" json:"training_type,omitempty"`
	Created                 *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=created" json:"created,omitempty"`
	Updated                 *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=updated" json:"updated,omitempty"`
	Deleted                 *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Group) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Group) GetTrainingDirectionId() []byte {
	if m != nil {
		return m.TrainingDirectionId
	}
	return nil
}

func (m *Group) GetTrainingDirectionNumber() int64 {
	if m != nil {
		return m.TrainingDirectionNumber
	}
	return 0
}

func (m *Group) GetStartYear() int64 {
	if m != nil {
		return m.StartYear
	}
	return 0
}

func (m *Group) GetPeriod() Period {
	if m != nil {
		return m.Period
	}
	return Period_Zero
}

func (m *Group) GetTrainingType() TrainingType {
	if m != nil {
		return m.TrainingType
	}
	return TrainingType_Bachelor
}

func (m *Group) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Group) GetUpdated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *Group) GetDeleted() *google_protobuf.Timestamp {
	if m != nil {
		return m.Deleted
	}
	return nil
}

type TrainingDirection struct {
	Id        []byte                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ShortName string                     `protobuf:"bytes,3,opt,name=short_name,json=shortName" json:"short_name,omitempty"`
	Created   *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=created" json:"created,omitempty"`
	Updated   *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=updated" json:"updated,omitempty"`
	Deleted   *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=deleted" json:"deleted,omitempty"`
}

func (m *TrainingDirection) Reset()                    { *m = TrainingDirection{} }
func (m *TrainingDirection) String() string            { return proto.CompactTextString(m) }
func (*TrainingDirection) ProtoMessage()               {}
func (*TrainingDirection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TrainingDirection) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TrainingDirection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TrainingDirection) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

func (m *TrainingDirection) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *TrainingDirection) GetUpdated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *TrainingDirection) GetDeleted() *google_protobuf.Timestamp {
	if m != nil {
		return m.Deleted
	}
	return nil
}

func init() {
	proto.RegisterType((*Group)(nil), "user.Group")
	proto.RegisterType((*TrainingDirection)(nil), "user.TrainingDirection")
	proto.RegisterEnum("user.Period", Period_name, Period_value)
	proto.RegisterEnum("user.TrainingType", TrainingType_name, TrainingType_value)
}

func init() { proto.RegisterFile("group.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x91, 0x4f, 0x8b, 0xd3, 0x50,
	0x14, 0xc5, 0x27, 0x7f, 0x9a, 0xb6, 0x77, 0xe2, 0xf0, 0x7c, 0x22, 0xc6, 0x01, 0xb1, 0x0c, 0x2e,
	0xca, 0x2c, 0x52, 0xa8, 0x82, 0x30, 0x4b, 0x11, 0xc5, 0x85, 0xc3, 0x10, 0xb2, 0xd1, 0x4d, 0x78,
	0xed, 0xbb, 0x66, 0x1e, 0x34, 0x79, 0xe1, 0xe6, 0x45, 0xe9, 0x27, 0xf2, 0x2b, 0xba, 0x94, 0xdc,
	0x26, 0x52, 0x1c, 0x61, 0x64, 0x76, 0xc9, 0x39, 0xe7, 0x07, 0xef, 0x9c, 0x0b, 0xa7, 0x25, 0xd9,
	0xae, 0x49, 0x1b, 0xb2, 0xce, 0xca, 0xb0, 0x6b, 0x91, 0xce, 0x5f, 0x96, 0xd6, 0x96, 0x3b, 0x5c,
	0xb1, 0xb6, 0xe9, 0xbe, 0xad, 0x9c, 0xa9, 0xb0, 0x75, 0xaa, 0x1a, 0x62, 0x17, 0x3f, 0x03, 0x98,
	0x7c, 0xec, 0x31, 0x79, 0x06, 0xbe, 0xd1, 0x89, 0xb7, 0xf0, 0x96, 0x71, 0xe6, 0x1b, 0x2d, 0xd7,
	0xf0, 0xd4, 0x91, 0x32, 0xb5, 0xa9, 0xcb, 0x42, 0x1b, 0xc2, 0xad, 0x33, 0xb6, 0x2e, 0x8c, 0x4e,
	0x7c, 0x8e, 0x3c, 0x19, 0xcd, 0xf7, 0xa3, 0xf7, 0x49, 0xcb, 0x2b, 0x78, 0xfe, 0x0f, 0xa6, 0xee,
	0xaa, 0x0d, 0x52, 0x12, 0x2c, 0xbc, 0x65, 0x90, 0x3d, 0xbb, 0xc3, 0x5d, 0xb3, 0x2d, 0x5f, 0x00,
	0xb4, 0x4e, 0x91, 0x2b, 0xf6, 0xa8, 0x28, 0x09, 0x39, 0x3c, 0x67, 0xe5, 0x0b, 0x2a, 0x92, 0xaf,
	0x20, 0x6a, 0x90, 0x8c, 0xd5, 0xc9, 0x64, 0xe1, 0x2d, 0xcf, 0xd6, 0x71, 0xda, 0x17, 0x4c, 0x6f,
	0x58, 0xcb, 0x06, 0x4f, 0xbe, 0x85, 0x47, 0x7f, 0x1e, 0xe0, 0xf6, 0x0d, 0x26, 0x11, 0x87, 0xe5,
	0x21, 0x9c, 0x0f, 0x56, 0xbe, 0x6f, 0x30, 0x8b, 0xdd, 0xd1, 0x9f, 0x7c, 0x03, 0xd3, 0x2d, 0xa1,
	0x72, 0xa8, 0x93, 0xe9, 0xc2, 0x5b, 0x9e, 0xae, 0xcf, 0xd3, 0xc3, 0x74, 0xe9, 0x38, 0x5d, 0x9a,
	0x8f, 0xd3, 0x65, 0x63, 0xb4, 0xa7, 0xba, 0x46, 0x33, 0x35, 0xbb, 0x9f, 0x1a, 0xa2, 0x3d, 0xa5,
	0x71, 0x87, 0x3d, 0x35, 0xbf, 0x9f, 0x1a, 0xa2, 0x17, 0xbf, 0x3c, 0x78, 0x9c, 0xff, 0xbd, 0xdd,
	0x9d, 0xab, 0x49, 0x08, 0x6b, 0x55, 0x21, 0x1f, 0x69, 0x9e, 0xf1, 0x37, 0x2f, 0x7b, 0x6b, 0xc9,
	0x15, 0xec, 0x04, 0xec, 0xcc, 0x59, 0xb9, 0xee, 0xed, 0xa3, 0xea, 0xe1, 0x83, 0xaa, 0x4f, 0x1e,
	0x54, 0x3d, 0xfa, 0xef, 0xea, 0x97, 0x2b, 0x88, 0x0e, 0x77, 0x96, 0x33, 0x08, 0xbf, 0x22, 0x59,
	0x71, 0x22, 0xa7, 0x10, 0xe4, 0x3f, 0xac, 0xf0, 0x7b, 0xe9, 0x83, 0xed, 0x48, 0x84, 0xfc, 0x65,
	0xbe, 0xa3, 0x98, 0x5c, 0x5e, 0x41, 0x7c, 0x7c, 0x6b, 0x19, 0xc3, 0xec, 0x9d, 0xda, 0xde, 0xe2,
	0xce, 0x92, 0x38, 0x91, 0x00, 0xd1, 0x67, 0xd5, 0x3a, 0x24, 0xe1, 0x49, 0x01, 0xf1, 0x8d, 0x6d,
	0x5d, 0x49, 0x4a, 0x77, 0xca, 0xa1, 0xf0, 0x37, 0x11, 0xbf, 0xe4, 0xf5, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xab, 0x87, 0x9b, 0x87, 0x4e, 0x03, 0x00, 0x00,
}
